var configHTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8">',
  '  <title>Configure Fuzzy Text</title>',
  '  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">',
  '  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">',
  '</head>',
  '<body>',
  '<div class="container">',
  '  <header><h1>Configure Fuzzy Text Int\'l</h1></header>',
  '  <form id="config" role="form" class="input-lg">',

  '    <fieldset><legend>&#9680; Invert colors</legend>',
  '      <div class="checkbox"><label>',
  '        <input type="checkbox" name="invert" value="yes"> Enable',
  '      </label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#8645; Shake to show date</legend>',
  '      <div class="checkbox"><label>',
  '        <input type="checkbox" name="show_date" value="yes" checked> Enable',
  '      </label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#8644; Text align</legend>',
  '      <div class="radio"><label><input type="radio" name="align" value="center" checked> &#8596; Center</label></div>',
  '      <div class="radio"><label><input type="radio" name="align" value="left"> &#8592; Left</label></div>',
  '      <div class="radio"><label><input type="radio" name="align" value="right"> &#8594; Right</label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#9698; Font size</legend>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="large" checked> L &mdash; Large</label></div>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="medium"> M &mdash; Medium</label></div>',
  '      <div class="radio"><label><input type="radio" name="font_size" value="small"> S &mdash; Small</label></div>',
  '    </fieldset>',

  '    <fieldset><legend>&#9760; Language</legend>',
  '      <select name="lang" class="form-control input-lg">',
  '        <option value="ca">Catal&#224;</option>',
  '        <option value="de">Deutsch</option>',
  '        <option value="en_GB">English (Great Britain)</option>',
  '        <option value="en_US">English (United States)</option>',
  '        <option value="es">Espa&#241;ol</option>',
  '        <option value="fr">Fran&#231;ais</option>',
  '        <option value="no">Norsk</option>',
  '        <option value="sv">Svenska</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset>',
  '      <a href="pebblejs://close" class="btn btn-lg btn-default">Cancel</a>',
  '      <button type="button" class="btn btn-lg btn-primary" id="b-submit">Save</button>',
  '    </fieldset>',
  '  </form>',
  '</div>',

  '<script src="https://code.jquery.com/jquery-1.11.0.min.js"><\/script>',
  '<script>',
  'function getParam(k) {',
  '  var val;',
  '  window.location.hash.replace(/(?:^|[#&])([a-z_]+)=([^&]+)/ig, function(_, key, v) {',
  '    if (k === key) val = decodeURIComponent(v);',
  '  });',
  '  return val;',
  '}',

  'function saveOptions() {',
  '  var p = {};',
  '  $("#config").serializeArray().forEach(function(x) { p[x.name] = x.value; });',
  '  return {',
  '    invert:     p.invert === "yes",',
  '    show_date:  p.show_date === "yes",',
  '    text_align: p.align || "center",',
  '    font_size:  p.font_size || "large",',
  '    lang:       p.lang',
  '  };',
  '}',

  'function applyOptions() {',
  '  var o = JSON.parse(getParam("options") || "{}");',
  '  if (o.invert === true || o.invert === "yes") $("[name=invert]").prop("checked", true);',
  '  if (o.show_date === false || o.show_date === "no") $("[name=show_date]").prop("checked", false);',
  '  if (o.text_align) $("[name=align][value=" + o.text_align + "]").prop("checked", true);',
  '  if (o.font_size)  $("[name=font_size][value=" + o.font_size + "]").prop("checked", true);',
  '  if (o.lang)       $("[name=lang]").val(o.lang);',
  '}',

  '$("#b-submit").click(function() {',
  '  document.location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(saveOptions()));',
  '});',
  'applyOptions();',
  '<\/script>',
  '</body>',
  '</html>'
].join('\n');
