var configHTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8">',
  '  <title>Configure Fuzzy Text</title>',
  '  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">',
  '  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">',
  '</head>',
  '<body>',
  '<div class="container">',
  '  <header><h1>Configure Fuzzy Text Int\'l</h1></header>',
  '  <form id="config" role="form" class="input-lg">',

  '    <fieldset><legend>Colors:</legend>',
  '      <div class="checkbox"><label>',
  '        <input type="checkbox" name="invert" value="on"> Invert colors',
  '      </label></div>',
  '    </fieldset>',

  '    <fieldset><legend>Date display:</legend>',
  '      <select name="date_trigger" class="form-control input-lg">',
  '        <option value="shake">Shake / wrist flick</option>',
  '        <option value="button">Select button</option>',
  '        <option value="both">Both</option>',
  '        <option value="disabled">Disabled</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset><legend>Text align:</legend>',
  '      <select name="align" class="form-control input-lg">',
  '        <option value="center">Center</option>',
  '        <option value="left">Left</option>',
  '        <option value="right">Right</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset><legend>Font size:</legend>',
  '      <select name="font_size" class="form-control input-lg">',
  '        <option value="large">Large</option>',
  '        <option value="medium">Medium</option>',
  '        <option value="small">Small</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset><legend>Language:</legend>',
  '      <select name="lang" class="form-control input-lg">',
  '        <option value="ca">Català</option>',
  '        <option value="de">Deutsch</option>',
  '        <option value="en_GB">English (Great Britain)</option>',
  '        <option value="en_US">English (United States)</option>',
  '        <option value="es">Español</option>',
  '        <option value="fr">Français</option>',
  '        <option value="no">Norsk</option>',
  '        <option value="sv">Svenska</option>',
  '      </select>',
  '    </fieldset>',

  '    <fieldset>',
  '      <a href="pebblejs://close" class="btn btn-lg btn-default">Cancel</a>',
  '      <button type="button" class="btn btn-lg btn-primary" id="b-submit">Save</button>',
  '    </fieldset>',
  '  </form>',
  '</div>',

  '<script src="https://code.jquery.com/jquery-1.11.0.min.js"><\/script>',
  '<script>',
  'function getParam(k) {',
  '  var val;',
  '  window.location.hash.replace(/(?:^|[#&])([a-z_]+)=([^&]+)/ig, function(_, key, v) {',
  '    if (k === key) val = decodeURIComponent(v);',
  '  });',
  '  return val;',
  '}',

  'function saveOptions() {',
  '  var p = {};',
  '  $("#config").serializeArray().forEach(function(x) { p[x.name] = x.value; });',
  '  return {',
  '    invert:        p.invert === "on",',
  '    date_trigger:  p.date_trigger || "shake",',
  '    text_align: p.align || "center",',
  '    font_size:  p.font_size || "large",',
  '    lang:       p.lang',
  '  };',
  '}',

  'function applyOptions() {',
  '  var o = JSON.parse(getParam("options") || "{}");',
  '  if (o.invert)        $("[name=invert]").prop("checked", true);',
  '  if (o.date_trigger)  $("[name=date_trigger]").val(o.date_trigger);',
  '  if (o.text_align)         $("[name=align]").val(o.text_align);',
  '  if (o.font_size)          $("[name=font_size]").val(o.font_size);',
  '  if (o.lang)               $("[name=lang]").val(o.lang);',
  '}',

  '$("#b-submit").click(function() {',
  '  document.location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(saveOptions()));',
  '});',
  'applyOptions();',
  '<\/script>',
  '</body>',
  '</html>'
].join('\n');
